---
- platform: mqtt
  name: "roomba"
  schema: state
  supported_features:
    - start
    - stop
    - return_home
    - battery
    - clean_spot
  availability_topic: "roomba/status"
  state_topic: "roomba/state"
  command_topic: "roomba/command"
